/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package traders.ManTrader;

import sesim.Account;
import sesim.Exchange;
import sesim.Exchange.OrderType;
import sesim.Quote;

/**
 *
 * @author tube
 */
public class EditOrderPanel extends javax.swing.JPanel {

    Exchange se;
    Account account;
    OrderType type;

    /**
     * Creates new form EditOrderPanel
     */
    public EditOrderPanel() {
        initComponents();
    }

    public EditOrderPanel(Exchange e, Account a, OrderType t) {
        this();
        se = e;
        account = a;
        type = t;
        this.loadFields();
    }

    private void loadFields() {
        System.out.printf("Load pressed\n");
        if (se == null) {
            return;
        }

        System.out.printf("Load now\n");

        Quote q = se.getBestPrice_0();
        Double price = q == null ? 0.0 : q.price;

        if (type == OrderType.BUYLIMIT) {
            this.limitSpinner.setValue(se.roundMoney(price));
            this.volumeSpinner.setValue(se.roundShares(account.getMoney() / price));
        }
        if (type == OrderType.SELLLIMIT) {
            this.limitSpinner.setValue(se.roundMoney(price));
            this.volumeSpinner.setValue(se.roundShares(account.getShares()));
        }
        setPrice();
    }

    private void setPrice() {
        double price = this.getPrice();
        String s = se.getMoneyFormatter().format(price);
        this.priceLabel.setText(s);
    }

    public double getPrice() {
        double price = this.getVolume() * this.getLimit();
        price = se.roundMoney(price);
        return price;
    }

    public double getVolume() {
        return (double) volumeSpinner.getValue();
    }

    public double getLimit() {
        return (double) limitSpinner.getValue();
    }

    /*    double limit = (double) limitSpinner.getValue();

        if (account == null) {
            System.out.printf("Account is null\n");
        }
        OrderType type = this.getOrderType();

        new Thread() {
            @Override
            public void run() {
               se.createOrder(account, type, volume, limit);
            }
        }.start();*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeComboBox = new javax.swing.JComboBox<>();
        limitSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        volumeSpinner = new javax.swing.JSpinner();
        loadValuesButton = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buy Limit", "Sell Limit", "Sell", "Buy" }));

        limitSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        limitSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                limitSpinnerStateChanged(evt);
            }
        });

        jLabel3.setText("Limit:");

        jLabel4.setText("Volume:");

        volumeSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        volumeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSpinnerStateChanged(evt);
            }
        });

        loadValuesButton.setText("Load");
        loadValuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadValuesButtonActionPerformed(evt);
            }
        });

        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(volumeSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(limitSpinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadValuesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(limitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(volumeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadValuesButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadValuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadValuesButtonActionPerformed
        this.loadFields();
    }//GEN-LAST:event_loadValuesButtonActionPerformed

    private void limitSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_limitSpinnerStateChanged
        setPrice();
    }//GEN-LAST:event_limitSpinnerStateChanged

    private void volumeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSpinnerStateChanged
        setPrice();
    }//GEN-LAST:event_volumeSpinnerStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    javax.swing.JSpinner limitSpinner;
    private javax.swing.JButton loadValuesButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JComboBox<String> typeComboBox;
    javax.swing.JSpinner volumeSpinner;
    // End of variables declaration//GEN-END:variables
}
