/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package traders.GroovyTrader;

import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import javax.swing.*;
import java.awt.*;
import org.fife.ui.rtextarea.RTextScrollPane;

import sesim.AutoTraderGui;

/**
 *
 * @author tube
 */
public class GroovyTraderGui extends AutoTraderGui {

    /**
     * Creates new form GrovyTraderGui
     */
    public GroovyTraderGui() {
       
        initComponents();
        
         setLayout(new BorderLayout());

        // 1. Erstellen Sie die RSyntaxTextArea
        RSyntaxTextArea textArea = new RSyntaxTextArea(20, 60);

        // 2. Setzen Sie den Syntax-Stil auf Groovy
        textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_GROOVY);

        // Optional: Zeilennummern anzeigen, etc.
        textArea.setCodeFoldingEnabled(true);

        // 3. Fügen Sie die TextArea zu einem RTextScrollPane hinzu (für Scrollen und Zeilennummern)
        RTextScrollPane sp = new RTextScrollPane(textArea);

        // 4. Fügen Sie die ScrollPane zum JPanel hinzu
        this.add(sp, BorderLayout.CENTER);
        
      setVisible(true);
    }

    // ... Beispiel Main-Methode zum Testen ...
    /*  public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Groovy Editor");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setContentPane(new GroovyEditorPanel());
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }*/
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
