/*
 * Copyright (c) 2017, 7u83 <7u83@mail.ru>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package traders.GroovyTrader;

//import org.fife.ui.rtextarea.AbstractSearchDialog;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.SearchEngine;
import org.fife.ui.rtextarea.SearchContext;
import org.fife.ui.rtextarea.SearchResult;
//import org.fife.ui.rtextarea.SearchDialog;
//import org.fife.ui.rtextarea.ReplaceDialog;
import java.awt.*;
import java.awt.event.KeyAdapter;
import org.fife.rsta.ui.search.ReplaceDialog;
import org.fife.rsta.ui.search.SearchListener;
import org.fife.ui.rtextarea.RTextScrollPane;

import sesim.AutoTraderGui;

/**
 *
 * @author tube
 */
public class GroovyTraderGui extends AutoTraderGui {

    RSyntaxTextArea textArea;
    GroovyTrader trader;

    /*    ReplaceDialog replaceDialog;
    SearchDialog searchDialog;*/

    /**
     * Creates new form GrovyTraderGui
     */
    public GroovyTraderGui(GroovyTrader trader) {
        this.trader = trader;

        initComponents();

        setLayout(new BorderLayout());

        // 1. Erstellen Sie die RSyntaxTextArea
        textArea = new RSyntaxTextArea(20, 60);

        // 2. Setzen Sie den Syntax-Stil auf Groovy
        textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_GROOVY);

        // Optional: Zeilennummern anzeigen, etc.
        textArea.setCodeFoldingEnabled(true);

        this.setText(trader.groovySourceCode);

        RTextScrollPane sp = new RTextScrollPane(textArea);

        // 4. Fügen Sie die ScrollPane zum JPanel hinzu
        this.add(sp, BorderLayout.CENTER);

        /*    // Such- und Ersetzen-Dialoge vorbereiten
        replaceDialog = new ReplaceDialog(null, textArea);
        searchDialog = new SearchDialog(null, textArea);

        // Tastenkürzel hinzufügen: STRG+F = Suche, STRG+H = Ersetzen
        textArea.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.isControlDown() && e.getKeyCode() == KeyEvent.VK_F) {
                    searchDialog.setVisible(true);
                } else if (e.isControlDown() && e.getKeyCode() == KeyEvent.VK_H) {
                    replaceDialog.setVisible(true);
                }
            }
        });*/
        setVisible(true);
    }

    void setText(String text) {
        textArea.setText(text);
    }

    String getText() {
        return textArea.getText();
    }

    @Override
    public void save() {
        this.trader.groovySourceCode = getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
