/*
 * Copyright (c) 2017, 7u83 <7u83@mail.ru>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package traders.ManTrader;

//import sesim.Exchange.Account;
import gui.Globals;
import java.text.DecimalFormat;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Formatter;
import sesim.Account;
import sesim.Market;
import sesim.Market.AccountListener;
import sesim.Market.QuoteReceiver;
import sesim.Quote;

/**
 *
 * @author 7u83 <7u83@mail.ru>
 */
public class AccountBalance extends javax.swing.JPanel implements QuoteReceiver {

    Account account;

    /**
     * Creates new form AccountBalance
     */
    public AccountBalance(Account a) {
        initComponents();
        this.account = a;
        if (a == null) {
            return;
        }
        a.getSe().addQuoteReceiver(this);
    }
    
    public AccountBalance(){
        this(null);
    }

    public void updateBalance(Account account) {
        DecimalFormat mf = account.getSe().getMoneyFormatter();
        //String s = mf.format(account.getMoney());
        cashLabel.setText(mf.format(account.getMoney()));
        DecimalFormat sf = account.getSe().getSharesFormatter();
        this.marginUsed.setText(mf.format(account.getMarginUsed()));

        this.freeMargin.setText(mf.format(account.getFreeMargin()));
        this.equity.setText(mf.format(account.getEquity()));

        float lp = account.getSe().getLastPrice();
        float total = lp * account.getShares() + account.getMoney();
        float iniTotal = lp * account.getInitialShares() + account.getInitialMoney();

        float perc =  total/(iniTotal/100)-100 ;

        String s = String.format("%s (%.1f%%)", (String) mf.format(total), perc);

        this.totalLabel.setText(s);
    }

    ExecutorService executor = Executors.newSingleThreadExecutor();
    boolean busy;
    boolean update;
    Quote quote;

    @Override
    public void UpdateQuote(Quote q) {
        if (q == null) {
            return;
        }

        if (busy) {
            quote = q;
            update = true;
            return;
        }
        busy = true;
        update = true;

        executor.submit(new Runnable() {
            @Override
            public void run() {
                try {

                    while (update) {
                        Quote q = quote;
                        update = false;
                        if (q == null) {
                            return;
                        }
                        javax.swing.SwingUtilities.invokeLater(() -> {

                            updateBalance(account);
                        });

                        try {
                            Thread.sleep(500);   // update rate is limited 50 Hz
                        } catch (InterruptedException e) {
                        }
                    }

                } finally {
                    busy = false;
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moneyLabelText = new javax.swing.JLabel();
        sharesLabelText = new javax.swing.JLabel();
        freeMargin = new javax.swing.JLabel();
        volAvailLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        marginUsed = new javax.swing.JLabel();
        sharesLabelText1 = new javax.swing.JLabel();
        cashLabel = new javax.swing.JLabel();
        equity = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        moneyLabelText.setText("Cash:");

        sharesLabelText.setText("Margin used");

        freeMargin.setText("0.0");

        volAvailLabel.setText("Free Margin");

        jLabel1.setText("Equity");

        marginUsed.setText("0");

        sharesLabelText1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        sharesLabelText1.setText("Total:");

        cashLabel.setText("0.0000");

        equity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        equity.setText("0");

        totalLabel.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalLabel.setText("0.0000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sharesLabelText1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volAvailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sharesLabelText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(moneyLabelText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(freeMargin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marginUsed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(equity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(cashLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moneyLabelText)
                    .addComponent(cashLabel))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volAvailLabel)
                    .addComponent(freeMargin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sharesLabelText)
                    .addComponent(marginUsed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sharesLabelText1)
                    .addComponent(totalLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cashLabel;
    private javax.swing.JLabel equity;
    private javax.swing.JLabel freeMargin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel marginUsed;
    private javax.swing.JLabel moneyLabelText;
    private javax.swing.JLabel sharesLabelText;
    private javax.swing.JLabel sharesLabelText1;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel volAvailLabel;
    // End of variables declaration//GEN-END:variables

}
