/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package traders.ManTrader;

import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.event.ChangeListener;
import javax.swing.text.DefaultFormatter;
import sesim.Account;
import sesim.Exchange;
import sesim.Order;
import sesim.Quote;

/**
 *
 * @author tube
 */
public class EditOrderPanel extends javax.swing.JPanel {

    Exchange se;
    Account account;
    byte type;

    /**
     * Creates new form EditOrderPanel
     */
    public EditOrderPanel() {
        initComponents();

        JSpinner spinner = limitSpinner;
        JComponent comp = spinner.getEditor();
        JFormattedTextField field = (JFormattedTextField) comp.getComponent(0);
        DefaultFormatter formatter = (DefaultFormatter) field.getFormatter();
        formatter.setCommitsOnValidEdit(true);

        limitSpinner.setEnabled(false);

        spinner = volumeSpinner;
        comp = spinner.getEditor();
        field = (JFormattedTextField) comp.getComponent(0);
        formatter = (DefaultFormatter) field.getFormatter();
        formatter.setCommitsOnValidEdit(true);

        spinner = stopSpinner;
        comp = spinner.getEditor();
        field = (JFormattedTextField) comp.getComponent(0);
        formatter = (DefaultFormatter) field.getFormatter();
        formatter.setCommitsOnValidEdit(true);
        this.stopSpinner.setEnabled(false);

    }

    public EditOrderPanel(Exchange e, Account a, byte type) {
        this();
        se = e;
        account = a;
        this.type = type;
        //this.loadFields();
    }

    public EditOrderPanel(Exchange e, Account a, Order o) {
        this();
        account = a;
        se = e;
        type = o.getType();

        this.volumeSpinner.setValue(o.getVolume());

        this.limitSpinner.setValue(o.getLimit());
        this.limitCheckBox.setSelected(o.hasLimit());
        this.limitSpinner.setEnabled(o.hasLimit());

        this.stopCheckBox.setSelected(o.hasStop());
        this.stopSpinner.setValue(o.getStop());
        this.stopSpinner.setEnabled(o.hasStop());
    }


    private void setPrice() {
        float price = this.getPrice();
        String s = se.getMoneyFormatter().format(price);
        this.priceLabel.setText(s);
    }

    public float getPrice() {
        float price = this.getVolume() * this.getLimit();
        price = se.roundMoney(price);
        return price;
    }

    public float getStop() {
        return (float) stopSpinner.getValue();
    }

    public float getVolume() {
        return (float) volumeSpinner.getValue();

    }

    public float getLimit() {
        return (float) limitSpinner.getValue();
    }
    
    public int getLeverage() {
        return (int) Integer.parseInt((String)leverageComboBox.getSelectedItem());
    }

    public byte getOrderType() {
        byte t = (byte) (this.type & 0x01);

        if (this.limitCheckBox.isSelected()) {
            t |= Order.LIMIT;
        }
        if (this.stopCheckBox.isSelected()) {
            t |= Order.STOP;
        }
        return t;
    }

    void addChangeListeners(ChangeListener c) {
        volumeSpinner.addChangeListener(c);
        limitSpinner.addChangeListener(c);
        limitCheckBox.addChangeListener(c);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeComboBox = new javax.swing.JComboBox<>();
        jCheckBox3 = new javax.swing.JCheckBox();
        limitSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        volumeSpinner = new javax.swing.JSpinner();
        loadValuesButton = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        setVolButton = new javax.swing.JButton();
        stopCheckBox = new javax.swing.JCheckBox();
        limitCheckBox = new javax.swing.JCheckBox();
        stopSpinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        leverageComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buy Limit", "Sell Limit", "Sell", "Buy" }));

        jCheckBox3.setText("fill or kill");

        limitSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        limitSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                limitSpinnerStateChanged(evt);
            }
        });

        jLabel4.setText("Volume:");

        volumeSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        volumeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSpinnerStateChanged(evt);
            }
        });

        loadValuesButton.setText("Set limit");
        loadValuesButton.setToolTipText("Set limit to the curent \ntraded price.");
        loadValuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadValuesButtonActionPerformed(evt);
            }
        });

        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("0.00");

        setVolButton.setText("Set vol");
        setVolButton.setToolTipText("Set the volume to the maximum \namount  you can buy with your \ncurrent cash balance.");
        setVolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setVolButtonActionPerformed(evt);
            }
        });

        stopCheckBox.setText("Stop");
        stopCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopCheckBoxActionPerformed(evt);
            }
        });

        limitCheckBox.setText("Lmit");
        limitCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitCheckBoxActionPerformed(evt);
            }
        });

        stopSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        stopSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                stopSpinnerStateChanged(evt);
            }
        });

        jButton1.setText("Set stop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        leverageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "5", "10", "100" }));
        leverageComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leverageComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Leverage:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leverageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(setVolButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadValuesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(limitCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volumeSpinner))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stopCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(stopSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volumeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(setVolButton)
                    .addComponent(priceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(limitCheckBox)
                        .addComponent(loadValuesButton)
                        .addComponent(leverageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopCheckBox)
                    .addComponent(stopSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadValuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadValuesButtonActionPerformed
        Quote q = se.getBestPrice_0();

        //if (type == Order.BUY) {
        this.limitSpinner.setValue((Float) se.roundMoney(q.getPrice()));
        //  this.volumeSpinner.setValue(se.roundShares(account.getMoney() / price));
        //}
        //if (type == Order.SELL) {
        //       this.limitSpinner.setValue((Float) se.roundMoney(q.getPrice()));
        //this.volumeSpinner.setValue(se.roundShares(account.getShares()));
        //}
        setPrice();
    }//GEN-LAST:event_loadValuesButtonActionPerformed

    private void limitSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_limitSpinnerStateChanged
        setPrice();
    }//GEN-LAST:event_limitSpinnerStateChanged

    private void volumeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSpinnerStateChanged
        setPrice();
    }//GEN-LAST:event_volumeSpinnerStateChanged

    private void setVolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setVolButtonActionPerformed
        Quote q = se.getBestPrice_0();
        // Float price = q == null ? 0.0f : q.getPrice();

        if ((type & 0x01) == Order.BUY) {
            float l = this.getLimit();
            if (l < 1 / se.shares_df) {
                l = 1 / 1 / se.shares_df;
            }

            this.volumeSpinner.setValue(se.roundShares(account.getCashAvailable() / l));

        }
        if (type == Order.SELL) {
            double avail = account.getSharesAvailable();

            this.volumeSpinner.setValue(se.roundShares(account.getSharesAvailable()));
        }        // TODO add your handling code here:
        this.volumeSpinner.revalidate();


    }//GEN-LAST:event_setVolButtonActionPerformed

    private void stopCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopCheckBoxActionPerformed
        stopSpinner.setEnabled(this.stopCheckBox.isSelected());        // TODO add your handling code here:
    }//GEN-LAST:event_stopCheckBoxActionPerformed

    private void stopSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_stopSpinnerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_stopSpinnerStateChanged

    private void limitCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitCheckBoxActionPerformed
        limitSpinner.setEnabled(this.limitCheckBox.isSelected());
    }//GEN-LAST:event_limitCheckBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Quote q = se.getBestPrice_0();

        //if (type == Order.BUY) {
        this.stopSpinner.setValue((Float) se.roundMoney(q.getPrice()));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void leverageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leverageComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leverageComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> leverageComboBox;
    private javax.swing.JCheckBox limitCheckBox;
    javax.swing.JSpinner limitSpinner;
    private javax.swing.JButton loadValuesButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton setVolButton;
    private javax.swing.JCheckBox stopCheckBox;
    javax.swing.JSpinner stopSpinner;
    private javax.swing.JComboBox<String> typeComboBox;
    javax.swing.JSpinner volumeSpinner;
    // End of variables declaration//GEN-END:variables
}
